num_steps: 3000000
batch_size: 128
lr: 0.00005
memory_size: 60000
gamma: 0.99
multi_step: 1
target_entropy_ratio: 0.6
#start_steps: 25000
start_steps: 25000
update_interval: 4
target_update_interval: 3000
use_per: True
dueling_net: True
num_eval_steps: 3000
max_episode_steps: 500
log_interval: 10
eval_interval: 10000 # Akash: change from 10k to 20k
#save_interval: 100000
